version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:1.17
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./build:/usr/share/nginx/html
    environment:
      - TZ=Asia/Shanghai
